"""Tests for ai_agent.get_ai_verdict — covers the live-OpenAI path with and
without the explicit VERDICT line.

The streaming path itself is not unit tested (it requires a live OpenAI
connection); the verdict-extraction logic is the part where prod regressed
to fallback. We pin both branches here so the next refactor cannot silently
swap to canned fallback text again.
"""

import asyncio

from ai_agent import get_ai_verdict
from models import AILogEntry


def _run(coro):
    return asyncio.get_event_loop().run_until_complete(coro)


def test_verdict_parsed_from_explicit_log_entry():
    """When OpenAI emits VERDICT-line, parser produces a ✅/❌ step."""
    log = [
        AILogEntry(step="🌡️ Анализ температуры", content="T=17°C, normal."),
        AILogEntry(
            step="✅ Финальный вердикт",
            content="SCORE: 72/100 | Approved due to severe drought signal.",
        ),
    ]
    scores = {"composite_score": 58, "approved": True}
    result = _run(
        get_ai_verdict(
            farmer_data={}, weather={}, ndvi={}, scores=scores, log_entries=log
        )
    )
    assert result.approved is True
    assert result.score == 72
    assert "Approved" in result.reasoning
    assert result.is_fallback is False


def test_live_ai_without_verdict_line_is_not_marked_as_fallback():
    """Regression: when GPT streams reasoning steps but does not output the
    VERDICT-line (e.g. truncated by max_tokens), we must still credit the
    AI's reasoning instead of swapping to canned fallback scenarios.
    """
    log = [
        AILogEntry(step="🌡️ Анализ температуры", content="T=17°C, влажность 75%."),
        AILogEntry(step="🌿 Анализ NDVI", content="NDVI=0.194, severe_drought."),
        AILogEntry(
            step="📊 Итоговое решение",
            content="Совокупно засуха подтверждена, рекомендую одобрить.",
        ),
    ]
    scores = {"composite_score": 58, "approved": True}
    result = _run(
        get_ai_verdict(
            farmer_data={}, weather={}, ndvi={}, scores=scores, log_entries=log
        )
    )
    assert result.is_fallback is False
    assert result.approved is True
    assert result.score == 58
    assert "засуха" in result.reasoning.lower()


def test_explicit_fallback_marker_keeps_is_fallback_true():
    """If [FALLBACK MODE] marker is present, downstream UI must show the
    fallback chip even if reasoning text is generated by the canned scenario.
    """
    log = [
        AILogEntry(
            step="🔄 Инициализация",
            content="[FALLBACK MODE] OpenAI API недоступен. Использую локальный эвристический агент.",
        ),
        AILogEntry(step="📊 Алгоритм", content="composite=58, approved."),
    ]
    scores = {"composite_score": 58, "approved": True}
    result = _run(
        get_ai_verdict(
            farmer_data={}, weather={}, ndvi={}, scores=scores, log_entries=log
        )
    )
    assert result.is_fallback is True


def test_no_log_entries_falls_through_to_fallback_engine():
    """Empty log → no OpenAI call ever happened → use the canned fallback."""
    scores = {"composite_score": 50, "approved": False}
    result = _run(
        get_ai_verdict(
            farmer_data={}, weather={}, ndvi={}, scores=scores, log_entries=[]
        )
    )
    assert result.is_fallback is True
